# Generated by Django 5.1.2 on 2024-11-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio_original', models.FloatField()),
                ('precio_descuento', models.FloatField()),
                ('stock', models.IntegerField()),
                ('categoria', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('nuevo', models.BooleanField()),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('imagen', models.FileField(upload_to='crud/')),
            ],
        ),
    ]
